PUBLIC LEN_SCREEN, LEN_NIRVANAP, LEN_PIETRO, LEN_BANK_06 
defc LEN_SCREEN = 3631 
defc LEN_NIRVANAP = 1695 
defc LEN_PIETRO = 16958 
defc LEN_BANK_06 = 4843 
EXTERN pietro_loader 
defc NEED_LOADER = pietro_loader 
